# Site settings
author: Shayan Mohsin
title: Electric Guitar Gallery 
header-img: img/home-bg.png
email: shaymotionfilms@gmail.com
copyright_name: Shayan Mohsin
description: > # this means to ignore newlines until "baseurl:"
  A CLI Data Gem Project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ShayMotion

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
